@startuml

!$DIAGRAM_TYPE = "SEQ"

!include https://raw.githubusercontent.com/golyshkin/puml_framework/refs/heads/main/settings/common.puml

'Configuration'
autonumber 1.1 "#.#"
skinparam SequenceMessagePadding 2
skinparam roundcorner 10
!pragma teoz false

@enduml