@startuml

!$DIAGRAM_TYPE = "SEQ"

!include https://gitlab.int.e-kama.com/open/architecture/dcp/sw-architecture/-/raw/master/settings/common.puml

'Configuration'
autonumber 1.1 "#.#"
skinparam SequenceMessagePadding 2
skinparam roundcorner 10

!if ( $CONFIG.TEOZ == true )
   !pragma teoz true
!endif

@enduml