@startuml

!$DIAGRAM_TYPE = "SM"

!include https://raw.githubusercontent.com/golyshkin/DEVPROM_link_fixer/refs/heads/main/tmp/sw_catalog/settings/common.puml

'Configuration'
skinparam linetype ortho
skinparam participantPadding 20
skinparam roundcorner 10
skinparam Shadowing false

top to bottom direction

@enduml