@startuml

!$DIAGRAM_TYPE = "SM"

!include https://raw.githubusercontent.com/golyshkin/puml_framework/refs/heads/main/settings/common.puml

'Configuration'
skinparam linetype ortho
skinparam participantPadding 20
skinparam roundcorner 10
skinparam Shadowing false

top to bottom direction

@enduml