@startuml

' Start Generic Compoenets Definition

$addActor( "external", "participant", "TBOX", "Telemetric Box", "system" )
$addActor( "external", "participant", "SGW",  "Secure Gateway", "system" )

' End Generic Compoenets Definition

!if ($HELP == true )
	note across #lightgreen: **Defined External Components**:\n\t\n**Note:** $COMP_NOTE\n\t\n$getActorList( "external" )
!endif

@enduml