@startuml

' Start Generic Compoenets Definition

$addActor( "generic", "actor", "User", "User Actor" )
$addActor( "generic", "actor", "System", "System Actor" )

' End Generic Compoenets Definition

!if ($HELP == true )
	note across #lightgreen: **Defined Generic Actors**:\n\t\n**Note:** $COMP_NOTE\n\t\n$getActorList( "generic" )
!endif

@enduml