@startuml

$addGroup( "sw_sfi", "Common" )
$addActor( "sw_sfi", "participant", "IVI_SFI", "Safety Island ASIL-B", "system" )

!if ( $CONFIG.SHOW_COMP == true )
  note across: <b>Include Command:</b> <i>!include</i> <i>$</i><i>URL_BASE/components/sw_sfi.puml</i>
  note across #lightblue: **SW SFI Components**:\n\t\n**Note:** $COMP_NOTE\n\t\n$getActorList( "sw_sfi" )
!endif

@enduml
